#!/usr/bin/env python3
"""Resolve a publisher RSS feed to a cached mpv playlist."""
import sys
sys.dont_write_bytecode = True
from lofi_feed import resolve

if __name__ == '__main__':
    try:
        print(resolve(*sys.argv[1:]))
    except (OSError, ValueError) as error:
        print(error, file=sys.stderr)
        sys.exit(1)
